-- Division in sql
DELIMITER $$

CREATE FUNCTION precise_division(a INT, b INT)
RETURNS DECIMAL(20, 10)
DETERMINISTIC
BEGIN
    IF b = 0 THEN
        RETURN 0;
    ELSE
        RETURN CAST(a AS DECIMAL(20, 10)) / CAST(b AS DECIMAL(20, 10));
    END IF;
END$$

DELIMITER ;

